### ISSUE TITLE
Unable to save or load advancement data

### ISSUE THREAD

**Issue by TheDeafCreeper** [ZockerAxel/CrazyAdvancementsAPI#11]
When attempting to save/load advancement data it fails with the error:
```
[18:30:56 ERROR]: Could not pass event PlayerJoinEvent to Woolsacre v1.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "eu.endercentral.crazy_advancements.CrazyAdvancementsAPI.getDataFolder()" because the return value of "eu.endercentral.crazy_advancements.CrazyAdvancementsAPI.getInstance()" is null
        at eu.endercentral.crazy_advancements.manager.AdvancementManager.getSavePath(AdvancementManager.java:711) ~[woolsacre.jar:?]
        at eu.endercentral.crazy_advancements.manager.AdvancementManager.getSaveFile(AdvancementManager.java:715) ~[woolsacre.jar:?]
        at eu.endercentral.crazy_advancements.manager.AdvancementManager.loadProgress(AdvancementManager.java:819) ~[woolsacre.jar:?]
        at eu.endercentral.crazy_advancements.manager.AdvancementManager.loadProgress(AdvancementManager.java:809) ~[woolsacre.jar:?]
        at net.prolieum.woolsacre.events.PlayerJoin.onPlayerJoin(PlayerJoin.kt:66) ~[woolsacre.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor138.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1708]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:365) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:341) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:577) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1708]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Server: git-Purpur-1708 (MC: 1.19)
CrazyAdvancementAPI: 2.1.10

**Comment by ZockerAxel** [comment]
You are shading the API into your plugin, when doing this the Instance is never initialized and support for saving among other things does not exist.
Shading is not supported officially, however you can try to instantiate the main class yourself to fix it
