### ISSUE TITLE
Request update for 1.20.2

### ISSUE THREAD

**Issue by Legoman99573** [ZockerAxel/CrazyAdvancementsAPI#16]
```applescript
[15:23:29 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CrazyAdvancementsAPI.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: 'void net.minecraft.advancements.Criterion.<init>(net.minecraft.advancements.CriterionInstance)'
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.2.jar:git-Paper-207]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.2.jar:git-Paper-207]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.2.jar:git-Paper-207]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-207]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-207]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512) ~[paper-1.20.2.jar:git-Paper-207]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-207]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-207]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-207]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.advancements.Criterion.<init>(net.minecraft.advancements.CriterionInstance)'
        at eu.endercentral.crazy_advancements.CrazyAdvancementsAPI.<clinit>(CrazyAdvancementsAPI.java:83) ~[CrazyAdvancementsAPI.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:495) ~[?:?]
        at java.lang.Class.forName(Class.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.2.jar:git-Paper-207]
        ... 9 more
```

**Comment by ZockerAxel** [comment]
Update is in the works, it's slightly more changes than a normal version update (more differences than 1.19->1.20 for reference) and until next weekend I don't have a lot of free time but I'm trying to get the update out as soon as I feasibly can.

I always work on updates as soon as I can so please stop nagging me about them.

**Comment by Legoman99573** [comment]
Not trying to nag about it, but alrighty.
