### ISSUE TITLE
Error with paper-126

### ISSUE THREAD

**Issue by Spartan9802** [ZockerAxel/CrazyAdvancementsAPI#2]
Hi,
I have an error with paper and CrazyAdvancementsAPI, could you correct it?
```[13:36:05 ERROR]: Could not pass event PlayerJoinEvent to CrazyAdvancementsAPI v1.13.7
java.util.NoSuchElementException: decoder
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.15.2.jar:git-Paper-143]
at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:320) ~[patched_1.15.2.jar:git-Paper-143]
at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:308) ~[patched_1.15.2.jar:git-Paper-143]
at com.comphenix.protocol.injector.netty.PipelineProxy.addAfter(PipelineProxy.java:54) ~[?:?]
at eu.endercentral.crazy_advancements.AdvancementPacketReceiver.listen(AdvancementPacketReceiver.java:60) ~[?:?]
at eu.endercentral.crazy_advancements.AdvancementPacketReceiver.initPlayer(AdvancementPacketReceiver.java:92) ~[?:?]
at eu.endercentral.crazy_advancements.CrazyAdvancements.onJoin(CrazyAdvancements.java:192) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-143]
at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:137) ~[?:?]
at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.joinWorld(AbstractLoginListenerPlay.java:145) ~[?:?]
at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.lambda$finishLogin$1(AbstractLoginListenerPlay.java:88) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1198) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

**Comment by ZockerAxel** [comment]
The code that isn't working is the code for listening to Packets sent by the client (=> Events for switching Advancement Tabs and closing the menu). Since it only doesn't work on paper, i suspect that because listening to packets isn't part of the API, it works differently and i don't know how. So for now Paper users will just not get a way to listen for these things
